### ISSUE TITLE
Review the Mobile view of the frontend and suggst changes

### ISSUE THREAD

**Issue by hariharan-leela** [Leela-Consultancy/PPDM_Dev_Prototype_Odoo#18]

**Comment by dhananjay-leela** [comment]
@indikale awaiting on repo updates.

**Comment by indikale** [comment]
@dhananjay-leela update is done, check and let me know

**Comment by hariharan-leela** [comment]
@indikale - Create a new Sprint to enhance the backend model to store the Website Category
@dhananjay-leela - When users give a website name, we will show its own as well as relative analytics for that category 

**Website Category:**

E-commerce: Sites like Amazon, eBay, etc.
Social Media: Sites like Facebook, Twitter, Instagram, etc.
News and Media: CNN, BBC, New York Times, etc.
Entertainment: Netflix, Spotify, etc.
Education: Coursera, Khan Academy, etc.
Utilities: Dropbox, Google Drive, etc.

**Type of Cookies:**

Essential Cookies: Cookies that are vital for website functionality.
Performance Cookies: Monitor website performance.
Third-party Cookies: Cookies set by a domain other than the one the user is visiting.

**Comment by dhananjay-leela** [comment]
@indikale 
@hariharan-leela 

Check out this Python library, which we can use for the categorization of websites that use a web crawler using NLP and ML algorithms to figure out what type of website it is.

**PyPi Website:** https://pypi.org/project/website-categorization/
**Official Website:** https://website-categorization.whoisxmlapi.com/api

**Comment by dhananjay-leela** [comment]
![Image](https://github.com/Leela-Consultancy/PPDM_Dev_Prototype_Odoo/assets/141627471/e8edaa09-46a0-4172-bdd7-2ccec08a6634)
![Image](https://github.com/Leela-Consultancy/PPDM_Dev_Prototype_Odoo/assets/141627471/752cb3fd-edca-4662-bfb6-b934ea7d4986)
![Image](https://github.com/Leela-Consultancy/PPDM_Dev_Prototype_Odoo/assets/141627471/d69ec19e-fb8a-4e8e-8297-1b36d34d8d57)
![Image](https://github.com/Leela-Consultancy/PPDM_Dev_Prototype_Odoo/assets/141627471/99169668-710d-42a0-9811-ef6de2815c42)

**Comment by dhananjay-leela** [comment]
Looking into creating a wireframe for the comparison UI we are trying to build on mobile. 
There are multiple ways we can achieve this but some of the paths i have explored are by using a Chrome extension called https://www.wirify.com/ which converts any website UI into a wireframe. Check the screenshot below.



![Image](https://github.com/Leela-Consultancy/PPDM_Dev_Prototype_Odoo/assets/141627471/b3f66fb5-0921-42ce-b5b2-2857f94d5820)

**Comment by dhananjay-leela** [comment]
Started also working on a figma project, by using a html.to.figma plugin i have managed to import web UI into figma project, you can view it here.

https://www.figma.com/file/e403KGRT8nUG1PbgnRgUoG/html.to.design-(Community)?type=whiteboard&node-id=1-474&t=oBru9uDAOAyTl0T9-0

**Comment by dhananjay-leela** [comment]
Continued working on the Figma to update the current design to adopt the cookies webpage currently built on odoo. 



![Image](https://github.com/Leela-Consultancy/PPDM_Dev_Prototype_Odoo/assets/141627471/60ce21a6-542b-4384-9eab-ecf69c28bd65)

**Comment by dhananjay-leela** [comment]
Downloaded a mock template and modified the layout to our use case. Work still in progress, learning figma as a tool 



![Image](https://github.com/Leela-Consultancy/PPDM_Dev_Prototype_Odoo/assets/141627471/ce9a1492-8845-433c-9773-25dbc81f0cd2)
